### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by RollinSafary** [paulstelzer/cordova-plugin-admob-mediation#2]
How can i use this plugin ? There is no interface in window to call something (however I couldn't find it).

**Comment by paulstelzer** [comment]
That is correct. It just installs frameworks for Android and iOS. In this case it only installs Unity Ads and Facebook. Inside Admob Mediation you can set the parameter. That's the reason no interface is needed. But you need a cordova admob plugin like https://github.com/ratson/cordova-plugin-admob-free
